apiVersion: v1
kind: Service
metadata:
  name: vote-app-service
  labels:
    name: vote-app-service
    tier: frontend
    app: voting-application
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    name: vote-app-pod
    tier: frontend
    app: voting-application