apiVersion: v1
kind: Service
metadata:
  name: postgresdb
  labels:
    name: postgres-service
    tier: backend
    app: voting-application
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
    tier: backend
    app: voting-application