apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels: 
    name: postgres-pod
    tier: backend
    app: voting-application
spec:
  containers:
    - name: postgres-container
      image: postgres:15-alpine
      ports:
        - containerPort: 5432
      env: 
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"