apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels: 
    name: postgres-deployment
    tier: backend
    app: voting-application
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      tier: backend
      app: voting-application
  template:
    metadata:
      name: postgres-pod
      labels: 
        name: postgres-pod
        tier: backend
        app: voting-application
    spec:
      containers:
        - name: postgres-container
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env: 
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"