apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    tier: backend
    app: voting-application
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-pod
    tier: backend
    app: voting-application